author: 'YC <yinso.chen@gmail.com>'
name: 'mockquery'
description: 'A Simple NodeJS jQuery Substitute'
version: '0.2.6'
repository:
  type: 'git'
  url: 'git@github.com:yinso/mockquery.git'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
main: './lib/mockquery.js'
dependencies:
  'coffee-script': '=1.7.1'
  underscore: '=1.6.0'
  htmlparser2: '=3.7.3'
  'pretty-data': '=0.40.0'
  loglet: '>=0.1.1'
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.1.0'
  pegjs: '=0.7.0' 
