// Generated by CoffeeScript 1.4.0
(function() {
  var Document, Element, Parser;

  Document = (function() {

    function Document() {}

    return Document;

  })();

  Element = (function() {

    function Element() {}

    return Element;

  })();

  Parser = (function() {

    function Parser() {}

    return Parser;

  })();

  Document.Element = Element;

  Document.Parser = Parser;

  module.exports = Document;

}).call(this);
