// Generated by CoffeeScript 1.4.0
(function() {
  var Document, Element, Entities, EventEmitter, XmlParser, entities, htmlParser, parse1, parse2, _,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  XmlParser = require('../grammar/xml');

  htmlParser = require('htmlparser2');

  EventEmitter = require('events').EventEmitter;

  _ = require('underscore');

  Entities = require('html-entities').AllHtmlEntities;

  entities = new Entities();

  parse1 = function(data, options) {
    var current, handler, level, parser, stack;
    if (options == null) {
      options = {
        xmlMode: true
      };
    }
    stack = [];
    current = null;
    level = 0;
    handler = {
      onopentag: function(name, attr) {
        var key, obj, val;
        for (key in attr) {
          val = attr[key];
          attr[key] = entities.decode(val);
        }
        obj = {
          element: name,
          attributes: attr,
          children: []
        };
        if (current !== null) {
          current.children.push(obj);
          stack.push(current);
        }
        current = obj;
        return level++;
      },
      ontext: function(txt) {
        if (level > 0) {
          return current.children.push(entities.decode(txt));
        }
      },
      onclosetag: function(name) {
        if (stack.length > 0) {
          current = stack.pop();
        }
        return level--;
      }
    };
    parser = new htmlParser.Parser(handler, options);
    parser.write(data);
    parser.end();
    return current;
  };

  parse2 = function(data) {
    return XmlParser.parse(data);
  };

  Document = (function() {

    Document.parse = function(text, options) {
      if (typeof text === 'string') {
        return new Document(parse1(text, options));
      } else if (text instanceof Object && text.element) {
        return new Document(text);
      } else {
        throw {
          error: 'unknown_document_structure',
          document: text
        };
      }
    };

    function Document(elt) {
      this.documentElement = elt instanceof Element ? elt.setOwnerDocument(this) : (elt = this.createElement(elt), elt.setOwnerDocument(this), elt);
      this._data = {};
    }

    Document.prototype.destroy = function() {
      return this.documentElement.destroy();
    };

    Document.prototype.data = function(key, val) {
      var res;
      if (arguments.length === 1) {
        res = this._data[key];
        if (res) {
          return res;
        } else {
          return void 0;
        }
      } else {
        return this._data[key] = val;
      }
    };

    Document.prototype.createElement = function(_arg, parent) {
      var attributes, children, element, elt, html;
      element = _arg.element, attributes = _arg.attributes, children = _arg.children;
      if (parent == null) {
        parent = null;
      }
      elt = this.initialize(element, attributes, children, parent);
      if (element === 'script') {
        html = elt.html();
        elt.empty();
        elt.append(html);
      }
      return elt;
    };

    Document.prototype.initialize = function(tag, attrs, children, parent) {
      var child, childElement, element, _i, _len;
      element = new Element(tag, attrs, null, parent);
      for (_i = 0, _len = children.length; _i < _len; _i++) {
        child = children[_i];
        if (typeof child === 'string') {
          element.append(child);
        } else {
          childElement = this.createElement(child, element);
          element.append(childElement);
        }
      }
      element.setOwnerDocument(this);
      return element;
    };

    Document.prototype.bind = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Document.prototype.on = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Document.prototype.unbind = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Document.prototype.clone = function() {
      return new Document(this.documentElement.clone());
    };

    Document.prototype.html = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.documentElement).html.apply(_ref, args);
    };

    Document.prototype.outerHTML = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.documentElement).outerHTML.apply(_ref, args);
    };

    return Document;

  })();

  Element = (function(_super) {

    __extends(Element, _super);

    function Element(tag, attributes, _parent, ownerDocument) {
      this._parent = _parent;
      this.ownerDocument = ownerDocument;
      this.tag = tag;
      this.attributes = attributes;
      this._data = {};
      this._children = [];
    }

    Element.prototype.destroy = function() {
      var child, _i, _len, _ref;
      delete this.ownerDocument;
      delete this._parent;
      _ref = this._children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (child instanceof Element) {
          child.destroy();
        }
      }
      return delete this._children;
    };

    Element.prototype.clone = function() {
      var child, elt, _i, _len, _ref;
      elt = this.ownerDocument.createElement({
        element: this.tag,
        attributes: _.extend({}, this.attributes),
        children: []
      });
      _ref = this._children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (child instanceof Element) {
          elt.append(child.clone());
        } else {
          elt.append(child);
        }
      }
      return elt;
    };

    Element.prototype.setOwnerDocument = function(doc) {
      var child, _i, _len, _ref, _results;
      if (!(doc instanceof Document)) {
        throw new Error("element.setOwnerDocument_not_document: " + doc);
      }
      this.ownerDocument = doc;
      _ref = this._children;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (child instanceof Element) {
          _results.push(child.setOwnerDocument(doc));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Element.prototype.parent = function() {
      return this._parent;
    };

    Element.prototype.children = function() {
      return _.filter(this._children, function(elt) {
        return elt instanceof Element;
      });
    };

    Element.prototype.removeChild = function(element) {
      this._children = _.without(this._children, element);
      return element._parent = null;
    };

    Element.prototype.detach = function() {
      if (this._parent) {
        return this._parent.removeChild(this);
      }
    };

    Element.prototype.append = function(elt, after) {
      var index;
      if (elt instanceof Element) {
        elt.detach();
        elt._parent = this;
      }
      if (after) {
        index = this._children.indexOf(after);
        return this._children.splice(index, 0, elt);
      } else {
        return this._children.push(elt);
      }
    };

    Element.prototype.prepend = function(elt, before) {
      var index;
      if (elt instanceof Element) {
        elt.detach();
        elt._parent = this;
      }
      if (before) {
        index = this._children.indexOf(before) - 1;
        if (index > -1) {
          return this._children.splice(index, 0, elt);
        } else {
          return this._children.unshift(elt);
        }
      } else {
        return this._children.unshift(elt);
      }
    };

    Element.prototype.after = function(elt) {
      return this._parent.append(elt, this);
    };

    Element.prototype.attr = function(key, val) {
      if (arguments.length === 1) {
        if (this.attributes.hasOwnProperty(key)) {
          return this.attributes[key];
        } else {
          return void 0;
        }
      } else {
        return this.attributes[key] = val;
      }
    };

    Element.prototype.removeAttr = function(key) {
      return delete this.attributes[key];
    };

    Element.prototype.data = function(key, val) {
      var res;
      if (arguments.length === 1) {
        res = this.attr("data-" + key);
        if (res) {
          return res;
        } else {
          return this._data[key];
        }
      } else {
        return this._data[key] = val;
      }
    };

    Element.prototype.getClasses = function() {
      var val;
      val = this.attr('class');
      if (val) {
        return val.split(/\s+/);
      } else {
        return [];
      }
    };

    Element.prototype.setClasses = function(classes) {
      return this.attr('class', classes.join(' '));
    };

    Element.prototype.addClass = function(key) {
      var classes;
      classes = this.getClasses();
      classes.push(key);
      return this.setClasses(classes);
    };

    Element.prototype.removeClass = function(key) {
      var classes;
      classes = this.getClasses();
      return this.setClasses(_.without(classes, key));
    };

    Element.prototype.isWhitespace = function(str) {
      if (typeof str === 'string') {
        return str.trim() === '';
      } else {
        return true;
      }
    };

    Element.prototype.html = function(str) {
      var child, elt, results, _i, _j, _len, _len1, _ref, _ref1, _results;
      if (arguments.length === 0) {
        results = [];
        _ref = this._children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          if (typeof child === 'string') {
            if (this.isWhitespace(child)) {
              results.push(child);
            } else {
              results.push(this.escape(child));
            }
          } else {
            results.push(child.outerHTML());
          }
        }
        return results.join('');
      } else {
        elt = parse1('<div>' + str + '</div>');
        this.empty();
        _ref1 = elt.children;
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          child = _ref1[_j];
          if (typeof child === 'string') {
            _results.push(this.append(child));
          } else {
            _results.push(this.append(this.ownerDocument.createElement(child, this)));
          }
        }
        return _results;
      }
    };

    Element.prototype.getCSS = function() {
      var key, keyval, result, val, _i, _len, _ref, _ref1;
      result = {};
      _ref = this.attr('style').split(/\s*;\s*/);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        keyval = _ref[_i];
        _ref1 = keyvals.split(/\s*=\s*/), key = _ref1[0], val = _ref1[1];
        result[key] = val;
      }
      return result;
    };

    Element.prototype.setCSS = function(keyvals) {
      var key, result, val;
      result = [];
      for (key in keyvals) {
        val = keyvals[key];
        result.push = "" + key + "=" + val;
      }
      return this.attr('style', result.join(";"));
    };

    Element.prototype.css = function(key, val) {
      var keyvals, result;
      if (arguments.length === 0) {
        throw new Error(".css_expects_at_least_1_arg");
      } else if (arguments.length === 1) {
        if (typeof key === 'string') {
          result = this.getCSS();
          return result[key];
        } else if (key instanceof Object) {
          return this.setCSS(key);
        } else {
          throw new Error("unsupported_css_argument: " + key);
        }
      } else {
        keyvals = this.getCSS();
        keyvals[key] = val;
        return this.setCSS(keyvals);
      }
    };

    Element.prototype.outerHTML = function(buffer) {
      var attrStr, child, _i, _len, _ref;
      if (buffer == null) {
        buffer = [];
      }
      attrStr = this.attrsToString();
      buffer.push("<", this.tag);
      if (attrStr !== '') {
        buffer.push(' ', attrStr);
      }
      if (this._children.length === 0) {
        buffer.push(' />');
      } else {
        buffer.push('>');
        _ref = this._children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          if (typeof child === 'string') {
            buffer.push(this.escape(child));
          } else {
            buffer.push(child.outerHTML());
          }
        }
        buffer.push("</" + this.tag + ">");
      }
      return buffer.join('');
    };

    Element.prototype.eltHTML = function() {
      return "<" + this.tag + " " + (this.attrsToString()) + " />";
    };

    Element.prototype.text = function(buffer) {
      var child, i, _i, _len, _ref;
      if (buffer == null) {
        buffer = [];
      }
      _ref = this._children;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        if (child instanceof Element) {
          child.text(buffer);
        } else {
          buffer.push(child);
        }
      }
      return buffer.join('');
    };

    Element.prototype.hasBinding = function() {
      return this.bindings !== null;
    };

    Element.prototype.attrsToString = function() {
      var buffers, key, val;
      buffers = (function() {
        var _ref, _results;
        _ref = this.attributes;
        _results = [];
        for (key in _ref) {
          val = _ref[key];
          if (!(val === null || val === void 0)) {
            _results.push("" + key + " = \"" + (this.escape(val)) + "\"");
          } else {
            _results.push('');
          }
        }
        return _results;
      }).call(this);
      return buffers.join(' ');
    };

    Element.prototype.empty = function() {
      var child, i, _i, _len, _ref;
      _ref = this._children;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        if (child instanceof Element) {
          child.empty();
          child._parent = null;
        }
      }
      return this._children = [];
    };

    Element.prototype.escape = function(str) {
      return entities.encode(str.toString());
    };

    Element.prototype.bind = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Element.prototype.unbind = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Element.prototype.on = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    Element.prototype.val = function(value) {
      if (arguments.length === 0) {
        if (this.tag === 'input' || this.tag === 'textarea' || this.tag === 'select') {
          if (this.attributes.hasOwnProperty('value')) {
            return this.attributes['value'];
          } else {
            return void 0;
          }
        }
      } else {
        if (this.tag === 'input' || this.tag === 'textarea' || this.tag === 'select') {
          return this.attributes.value = value;
        } else {

        }
      }
    };

    return Element;

  })(EventEmitter);

  Document.Element = Element;

  module.exports = Document;

}).call(this);
