// Generated by CoffeeScript 1.4.0
(function() {
  var Document, Element, EventEmitter, MockQuery, Node, Parser, Selector, Serializer, XmlParser, entities, fromJSON, fs, get, getJSON, http, https, jsonElement, kvs, load, loadHTML, loglet, path, postJSON, qs, readFile, readFileSync, statusCodeToError, url, _,
    __slice = [].slice;

  _ = require('underscore');

  EventEmitter = require('events').EventEmitter;

  Node = require('./node');

  Document = require('./document');

  Element = require('./element');

  Selector = require('./selector');

  XmlParser = require('../grammar/xml');

  Parser = require('./parser');

  Serializer = require('./serializer');

  http = require('http');

  https = require('https');

  url = require('url');

  kvs = require('./kvs');

  qs = require('querystring');

  fs = require('fs');

  path = require('path');

  loglet = require('loglet');

  entities = require('./entities');

  MockQuery = (function() {

    function MockQuery(elements, context) {
      var elt, i, _i, _len;
      this.context = context;
      for (i = _i = 0, _len = elements.length; _i < _len; i = ++_i) {
        elt = elements[i];
        this[i] = elt;
        this.length = elements.length;
      }
    }

    MockQuery.prototype.html = function(htmlString) {
      var elt, i, _i, _len;
      if (arguments.length === 0) {
        if (this.length > 0) {
          return this[0].html();
        } else {
          return '';
        }
      } else {
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          elt.html(htmlString);
        }
        return this;
      }
    };

    MockQuery.prototype.outerHTML = function() {
      if (this.length > 0) {
        return this[0].outerHTML();
      } else {
        return '';
      }
    };

    MockQuery.prototype.text = function() {
      var arg, elt, _i, _len, _results;
      if (arguments.length === 0) {
        if (this.length > 0) {
          return this[0].text();
        } else {
          return '';
        }
      } else {
        arg = arguments[0];
        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          elt = this[_i];
          _results.push(elt.text(arg));
        }
        return _results;
      }
    };

    MockQuery.prototype.attr = function(key, val) {
      var elt, _i, _len;
      if (arguments.length === 1) {
        if (this.length > 0) {
          return this[0].attr(key);
        } else {
          return null;
        }
      } else {
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          elt = this[_i];
          elt.attr(key, val);
        }
        return this;
      }
    };

    MockQuery.prototype.bind = function() {
      var args, elt, i, _i, _len;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.bind.apply(elt, args);
      }
      return this;
    };

    MockQuery.prototype.unbind = function() {
      var args, elt, i, _i, _len;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.unbind.apply(elt, args);
      }
      return this;
    };

    MockQuery.prototype.css = function() {
      var arg, elt, i, _i, _len;
      arg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (arguments.length === 1) {
        if (this.length > 0) {
          return this[0].css(arg[0]);
        } else {
          return null;
        }
      } else {
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          elt.css.apply(elt, arg);
        }
        return this;
      }
    };

    MockQuery.prototype.addClass = function(cls) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.addClass(cls);
      }
      return this;
    };

    MockQuery.prototype.removeClass = function(cls) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.removeClass(cls);
      }
      return this;
    };

    MockQuery.prototype.children = function() {
      var item, total, _i, _len;
      total = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        item = this[_i];
        total = total.concat(item.children(0));
      }
      return new MockQuery(total, this.context);
    };

    MockQuery.prototype.appendTo = function(parent) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        parent.append(elt);
      }
      return this;
    };

    MockQuery.prototype.detach = function() {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.detach();
      }
      return this;
    };

    MockQuery.prototype.removeAttr = function(key) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.removeAttr(key);
      }
      return this;
    };

    MockQuery.prototype.empty = function() {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.empty();
      }
      return this;
    };

    MockQuery.prototype.on = function() {
      return this;
    };

    MockQuery.prototype.filter = function(selector) {
      var elt, i, result, _i, _len;
      selector = new Selector(selector);
      result = [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        if (elt instanceof Document) {
          selector.matchOne(elt.documentElement, result);
        } else {
          selector.matchOne(elt, result);
        }
      }
      return new MockQuery(result, this.context);
    };

    MockQuery.prototype.add = function(selector, context) {
      var results, sel;
      if (context == null) {
        context = this.context;
      }
      sel = new Selector(selector);
      results = sel.run(context);
      return new MockQuery(this.toArray().concat(results), this.context);
    };

    MockQuery.prototype.toArray = function() {
      var elt, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        elt = this[_i];
        _results.push(elt);
      }
      return _results;
    };

    MockQuery.prototype.has = function(selector) {
      var elt, result, _i, _j, _len, _len1;
      if (selector instanceof Element) {
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          elt = this[_i];
          if (elt === selector) {
            return new MockQuery([elt], this.context);
          }
        }
        return new MockQuery([], this.context);
      } else {
        selector = new Selector(selector);
        result = [];
        for (_j = 0, _len1 = this.length; _j < _len1; _j++) {
          elt = this[_j];
          selector.match(elt, result);
        }
        return new MockQuery(result, this.context);
      }
    };

    MockQuery.prototype.data = function(key, val) {
      var elt, i, _i, _len, _results;
      if (arguments.length === 1) {
        if (this.length === 0) {
          return null;
        } else {
          return this[0].data(key);
        }
      } else {
        _results = [];
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          _results.push(elt.data(key, val));
        }
        return _results;
      }
    };

    MockQuery.prototype.remove = function() {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.detach();
      }
      return this;
    };

    MockQuery.prototype.clone = function() {
      var elements, elt, i;
      elements = (function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          _results.push(elt.clone());
        }
        return _results;
      }).call(this);
      return new MockQuery(elements, this.context);
    };

    MockQuery.prototype.not = function(selector) {
      var elt, i, res, result, sel, _i, _j, _len, _len1;
      if (selector instanceof Array) {
        result = [];
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          if (!_.contains(selector, elt)) {
            result.push(elt);
          }
        }
        return new MockQuery(result, this.context);
      } else if (typeof selector === 'string') {
        sel = new Selector(selector);
        result = [];
        for (i = _j = 0, _len1 = this.length; _j < _len1; i = ++_j) {
          elt = this[i];
          res = sel.matchOne(elt, result);
          if (!res) {
            result.push(elt);
          }
        }
        return new MockQuery(result, this.context);
      } else {
        throw new Error("unsupported_not_selector: " + selector);
      }
    };

    MockQuery.prototype.prepend = function(element) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        if (i === 0) {
          elt.prepend(element);
        } else {
          elt.prepend(element.clone());
        }
      }
      return this;
    };

    MockQuery.prototype.append = function(element) {
      var elt, i, _i, _j, _k, _len, _len1, _len2;
      if (element instanceof MockQuery) {
        for (_i = 0, _len = element.length; _i < _len; _i++) {
          elt = element[_i];
          this.append(elt);
        }
      } else if (element instanceof Array) {
        for (_j = 0, _len1 = element.length; _j < _len1; _j++) {
          elt = element[_j];
          this.append(elt);
        }
      } else {
        for (i = _k = 0, _len2 = this.length; _k < _len2; i = ++_k) {
          elt = this[i];
          if (i === 0) {
            elt.append(element);
          } else {
            elt.append(element.clone());
          }
        }
      }
      return this;
    };

    MockQuery.prototype.after = function(element) {
      var elt, i, _i, _len;
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        elt.after(element);
      }
      return this;
    };

    MockQuery.prototype.val = function(value) {
      var elt, i, _i, _len;
      if (arguments.length === 0) {
        if (this.length > 0) {
          return this[0].val();
        }
      } else {
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          elt.val(value);
        }
        return this;
      }
    };

    MockQuery.prototype.index = function() {
      if (this.length === 0) {
        return null;
      } else {
        if (!this[0]._parent) {
          return 0;
        } else {
          return this[0]._parent.children().indexOf(this[0]);
        }
      }
    };

    MockQuery.prototype.each = function(cb) {
      var elt, i, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        _results.push(cb.call(elt, i, elt));
      }
      return _results;
    };

    MockQuery.prototype.map = function(cb) {
      var elt, i, result;
      result = (function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
          elt = this[i];
          _results.push(cb.call(elt, i, elt));
        }
        return _results;
      }).call(this);
      return result;
    };

    MockQuery.prototype.parent = function() {
      var elt, i, parent, results, _i, _len;
      results = [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        elt = this[i];
        parent = elt.parent();
        if (parent) {
          results.push(parent);
        }
      }
      return new MockQuery(results, this.context);
    };

    return MockQuery;

  })();

  statusCodeToError = function(statusCode) {
    if (statusCode >= 500) {
      return new Error("server_error: " + statusCode);
    } else if (statusCode >= 400) {
      return new Error("bad_request: " + statusCode);
    } else if (statusCode >= 300) {
      return null;
    } else if (statusCode >= 200) {
      return null;
    } else {
      return null;
    }
  };

  getJSON = function(uri, data, cb) {
    /*
      if arguments.length == 2
        cb = data
        data = {}
      try
        data = kvs.flatten data
        options = url.parse uri
        options.query = _.extend {}, options.query, data
        console.log 'getJSON', uri, options
        protocol =
          if options.protocol == 'https:'
            https
          else if options.protocol == 'http:'
            http
          else
            throw new Error("unsupported_protocol: #{uri}")
        req = protocol.request options, (res) ->
          output = []
          res.setEncoding 'utf8'
          res.on 'data', (chunk) ->
            console.log 'getJSON.response.chunk', chunk
            output.push chunk
          res.on 'end', () ->
            try
              obj = JSON.parse output.join('')
              console.log 'getJSON.response.end', obj
              cb obj, res.statusCode
            catch e
              cb e, 500
        req.on 'error', cb
      catch e
        cb e, 500
    */

  };

  postJSON = function(uri, data, cb) {
    /*
      if arguments.length == 2
        cb = data
        data = {}
      try
        data = kvs.flatten data
        options = url.parse uri
        protocol =
          if options.protocol == 'https'
            https
          else if options.protocol == 'http'
            http
          else
            throw new Error("unsupported_protocol: #{uri}")
        req = protocol.request options, (res) ->
          output = []
          res.setEncoding 'utf8'
          res.on 'data', (chunk) ->
            output.push chunk
          res.on 'end', () ->
            try
              obj = JSON.parse output.join('')
              cb obj, res.statusCode
            catch e
              cb e, 500
        req.on 'error', cb
        query = qs.stringify(data)
        req.setHeader 'Content-Type', 'application/x-www-form-urlencoded'
        req.setHeader 'Content-Length', query.length
        req.write query
        req.end()
      catch e
        cb e, 500
    */

  };

  /*
  jQuery API... http://api.jquery.com/jQuery/
  
  not yet implemented all of this... note the options are additional on top for parsing both html (case insensitive) & xml
      
  jQuery( selector [, context ] )
    jQuery( selector [, context ] )
    jQuery( element )
    jQuery( elementArray )
    jQuery( object )
    jQuery( selection )
    jQuery()
  jQuery( html [, ownerDocument ] )
    jQuery( html [, ownerDocument ] )
    jQuery( html, attributes )
  jQuery( callback )
    jQuery( callback )
  */


  load = function(document, options) {
    var query;
    if (typeof document === 'string') {
      document = Parser.parseDocument(document, options);
    } else if (document instanceof Buffer) {
      document = Parser.parseDocument(document.toString('utf8'), options);
    } else if (document instanceof Document) {
      document = document;
    }
    query = function(selector, context) {
      var elt, sel;
      if (context == null) {
        context = document;
      }
      if (selector instanceof Element) {
        return new MockQuery([selector], document);
      } else if (selector instanceof Document) {
        return new MockQuery([selector], document);
      } else if (typeof selector === 'string' && selector.match(/<[^>]+>/)) {
        elt = Parser.parseElement(selector, document);
        if (!(context instanceof Document)) {
          _.extend(elt.attributes, context);
        }
        return new MockQuery([elt], document);
      } else if (typeof selector === 'string') {
        sel = new Selector(selector);
        return new MockQuery(sel.run(document, true), document);
      } else {
        throw new Error("unknown_selector_type: " + selector);
      }
    };
    query.fn = query.prototype;
    query.document = document;
    query.fn.getJSON = getJSON;
    query.fn.destroy = function() {
      return query.document.destroy();
    };
    return query;
  };

  loadHTML = function(document) {
    return load(document, {
      xmlMode: false
    });
  };

  readFile = function(filePath, cb) {
    return fs.readFile(filePath, 'utf8', function(err, data) {
      var ext, options;
      if (err) {
        return cb(err);
      } else {
        ext = path.extname(filePath);
        options = ext === '.html' || ext === '.htm' ? {
          xmlMode: false
        } : {
          xmlMode: true
        };
        return cb(null, load(data, options));
      }
    });
  };

  readFileSync = function(filePath) {
    var ext, options;
    ext = path.extname(filePath);
    options = ext === '.html' || ext === '.htm' ? {
      xmlMode: false
    } : {
      xmlMode: true
    };
    return load(fs.readFileSync(filePath, 'utf8'), options);
  };

  get = function(uri, cb) {
    var buffer, parsed, proto, req;
    parsed = url.parse(uri);
    proto = parsed.protocol === 'https:' ? https : http;
    buffer = new Buffer('');
    return req = proto.get(parsed, function(res) {
      if (res.statusCode >= 400) {
        cb({
          error: 'http',
          statusCode: res.statusCode,
          status: res.status
        });
        res.end();
        return;
      }
      res.on('data', function(data) {
        return buffer = Buffer.concat([buffer, data]);
      });
      return res.on('end', function() {
        var $, contentType;
        try {
          contentType = res.getHeader('content-type');
          if (contentType.match(/xml/i)) {
            return $ = load(buffer.ToString(), {
              xmlMode: true
            });
          } else if (contentType.match(/html/i)) {
            return $ = load(buffer.ToString(), {
              xmlMode: false
            });
          } else {
            return cb({
              error: 'invalid_content_type',
              contentType: contentType
            });
          }
        } catch (e) {
          return cb(e);
        }
      });
    });
  };

  fromJSON = function(json) {
    var elt;
    elt = Node.serializer().fromJSON(json);
    return load(new Document(elt));
  };

  jsonElement = function(json) {
    return Node.serializer().fromJSON(json);
  };

  module.exports = {
    load: load,
    loadHTML: loadHTML,
    readFile: readFile,
    readFileSync: readFileSync,
    get: get,
    Document: Document,
    Selector: Selector,
    Element: Element,
    parseDocument: Parser.parseDocument,
    parseElement: Parser.parseElement,
    fromJSON: fromJSON,
    jsonElement: jsonElement,
    entities: entities
  };

}).call(this);
