// Generated by CoffeeScript 1.4.0
(function() {
  var Node, entities, fromJSON, innerHTML, loglet, outerHTML, toJSON, toText, _attrsToString, _toHTML, _toText;

  Node = require('./node');

  entities = require('./entities');

  loglet = require('loglet');

  outerHTML = function(node, options) {
    var Document, Element, buffer;
    if (options == null) {
      options = {};
    }
    Element = Node.type(Node.ELEMENT_NODE);
    Document = Node.type(Node.DOCUMENT_NODE);
    buffer = [];
    _toHTML(node, buffer, options);
    return buffer.join('');
  };

  innerHTML = function(node, options) {
    var Document, Element, buffer, child, _i, _len, _ref;
    if (options == null) {
      options = {};
    }
    Element = Node.type(Node.ELEMENT_NODE);
    Document = Node.type(Node.DOCUMENT_NODE);
    buffer = [];
    _ref = node._children;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      _toHTML(child, buffer, options);
    }
    return buffer.join('');
  };

  _attrsToString = function(attributes, options) {
    var buffer, key, val;
    if (attributes == null) {
      attributes = {};
    }
    buffer = (function() {
      var _results;
      _results = [];
      for (key in attributes) {
        val = attributes[key];
        if (!(val === null || val === void 0)) {
          _results.push("" + key + " = \"" + (entities.encode(val, options)) + "\"");
        } else {
          _results.push('');
        }
      }
      return _results;
    })();
    return buffer.join(' ');
  };

  _toHTML = function(node, buffer, options) {
    var attrStr, child, _i, _len, _ref;
    if (typeof node === 'string') {
      buffer.push(entities.encode(node, options));
      return;
    }
    attrStr = _attrsToString(node.attributes, options);
    buffer.push('<', node.tag);
    if (attrStr !== '') {
      buffer.push(' ', attrStr);
    }
    if (!node._children) {
      console.log('__toHTML:no_children', node);
    }
    if (node._children.length === 0) {
      return buffer.push(' />');
    } else {
      buffer.push('>');
      _ref = node._children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (typeof child === 'string') {
          buffer.push(entities.encode(child, options));
        } else {
          _toHTML(child, buffer, options);
        }
      }
      return buffer.push("</" + node.tag + ">");
    }
  };

  toText = function(node) {
    var buffer;
    buffer = [];
    _toText(node, buffer);
    return buffer.join('');
  };

  _toText = function(node, buffer) {
    var child, i, _i, _len, _ref, _results;
    if (typeof node === 'string') {
      return buffer.push(node);
    } else {
      _ref = node._children;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        _results.push(_toText(child, buffer));
      }
      return _results;
    }
  };

  toJSON = function(node) {
    var child, obj, _i, _len, _ref;
    if (typeof node === 'string') {
      return node;
    } else {
      obj = {
        element: node.tag,
        attributes: node.attributes,
        children: []
      };
      _ref = node._children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        obj.children.push(toJSON(child));
      }
      return obj;
    }
  };

  fromJSON = function(obj, Element) {
    var child, elt, _i, _len, _ref;
    if (Element == null) {
      Element = Node.type(Node.ELEMENT_NODE);
    }
    if (typeof obj === 'string') {
      return obj;
    } else {
      elt = new Element(obj.element, obj.attributes || {}, []);
      _ref = obj.children || [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        elt.append(fromJSON(child, Element));
      }
      return elt;
    }
  };

  Node.registerSerializer(module.exports = {
    outerHTML: outerHTML,
    innerHTML: innerHTML,
    toText: toText,
    toJSON: toJSON,
    fromJSON: fromJSON
  });

}).call(this);
